config/routes.rb
Rails.application.routes.draw do
  resources :pins

  devise_for :users
  root 'pages#home'
  get 'about' => 'pages#about'

end

app/models/pin.rb
class Pin < ActiveRecord::Base
	belongs_to :user

	do_not_validate_attachment_file_type :image

	has_attached_file :image, :styles => { :medium => "300x300>", :thumb => "100x100>" }
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :pins
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end
end

app/controllers/pins_controller.rb
class PinsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :set_pin, only: [:show, :edit, :update, :destroy]
  before_action :correct_user, only: [:edit, :update, :destroy]
  respond_to :html

  def index
    @pins = Pin.all
    respond_with(@pins)
  end

  def show
    respond_with(@pin)
  end

  def new
    #@pin = Pin.new
    # to enable the pin automatically being assigned to the user
   @pin = current_user.pins.build
    respond_with(@pin)
  end

  def edit
  end

  def create

    #@pin = Pin.new(pin_params)
    #to enable pins being automatically assigned to users
    @pin = current_user.pins.build
    @pin.save
    respond_with(@pin)
  end

  def update
    @pin.update(pin_params)
    respond_with(@pin)
  end

  def destroy
    @pin.destroy
    respond_with(@pin)
  end

  private
    def set_pin
      @pin = Pin.find(params[:id])
    end

    def correct_user
      @pin = current_user.pins.find_by(id: params[:id])
      redirect_to pins_path if @pin.nil?
    end

    def pin_params
      params.require(:pin).permit(:description, :image)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/pins_helper.rb
module PinsHelper
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">Pinteresting</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home", root_path %> </li>
        <li><%= link_to "About", about_path %> </li>
        <li><%= link_to "#", new_user_registration_path %> </li>
        <li><%= link_to "Sign In", new_user_session_path %> </li>
        <% if user_signed_in? %>
          <li><%= link_to 'New Pin', new_pin_path %></li>
          <li><%= link_to "Log out", destroy_user_session_path, method: :get %></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>
<div class="container">

app/views/layouts/application.html.erb
<!DOCTYPE html>

<%= javascript_include_tag :all %>

<html>
<head>
  <title>Pinteresting</title>
  <%= stylesheet_link_tag    'application', media: 'all'  %>
  <%= javascript_include_tag 'default' %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>

<%= render "layouts/header" %>
<div class="container">
	<% flash.each do |name, msg| %>
		<%= content_tag(:div, msg, class: "alert alert-info") %>
	<% end %>
	<%= yield %>
</div>
</body>
</html>

app/views/pages/about.html.erb

<h1> About Page </h1>
<p> We are working on our first Rails App!</p>
<p> Look us up on <%= link_to "The Internet!", "https://www.google.com.co" %>. </p>

app/views/pages/home.html.erb
<div class="jumbotron">
	<h1>Welcome to my app</h1>
	<% if user_signed_in? %>
	#something
	<% else %>
	<p>Click Here to <%= link_to "Sign Up", new_user_registration_path, class: "btn btn-primary btn-lg" %> </p>
	<p>Click Here to <%= link_to "Log In", new_user_session_path, class: "btn btn-primary btn-lg" %> </p>
	<% end %>
</div>

app/views/pins/_form.html.erb
<%= form_for @pin, html: { multipart: true } do |f| %>
  <% if @pin.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@pin.errors.count, "error") %> prohibited this pin from being saved:</h2>

      <ul>
      <% @pin.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group">
    <%= f.label :image %><br>
    <%= f.file_field :image, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/pins/edit.html.erb
<h1>Editing pin</h1>

<%= render 'form' %>

<%= link_to 'Show', @pin %> |
<%= link_to 'Back', pins_path %>

app/views/pins/index.html.erb
<div id="pins" class="transitions-enabled">
  <% @pins.each do |pin| %>
    <div class="box panel panel-default">
      <%= image_tag pin.image.url() %>
     <div class="panel-body">
        <%= pin.description %>
        <% if pin.user %>
          <% if pin.user != current_user %>
            <%= pin.user.email %>
            <% else %>
             You
          <% end %>
          <% else %>
        <% end %>
        <%= link_to 'Show', pin %>
        <% if pin.user == current_user %>
          <%= link_to 'Edit', edit_pin_path(pin) %>
          <%= link_to 'Destroy', pin, method: :delete, data: { confirm: 'Are you sure?' } %>
        <% end %>
      </div>
    </div>
  <% end %>
</div>

app/views/pins/new.html.erb
<h1>New pin</h1>

<%= render 'form' %>

<%= link_to 'Back', pins_path %>

app/views/pins/show.html.erb
<%= image_tag @pin.image.url(:medium) %>
<p>
  <strong>Description:</strong>
  <%= @pin.description %>
</p>
 <% if @pin.user == current_user %>
	<%= link_to 'Edit', edit_pin_path(@pin) %> |
<% end %>
<%= link_to 'Back', pins_path %>